Add Ruby 2.6.9 version for CVE-2021-41817, CVE-2021-41819
ltvco/bv-ruby pull request #5
Opened 2021-11-24 18:48 UTC by kamoh

Adds Ruby 2.6.9 image for these CVEs:

Issues summary:
https://www.ruby-lang.org/en/news/2021/11/24/ruby-2-6-9-released/

CVE-2021-41817: https://www.ruby-lang.org/en/news/2021/11/15/date-parsing-method-regexp-dos-cve-2021-41817/
CVE-2021-41819: https://www.ruby-lang.org/en/news/2021/11/24/cookie-prefix-spoofing-in-cgi-cookie-parse-cve-2021-41819/

2021-11-24 19:55 UTC, rvalenciano commented
Did we run any of the ruby 2.6.X current images with this new image? This can be done locally by building the image in your local machine and using it in the Dockerfile of core for instance. If tests pass and you are able to run the app, and do things with it (like logging in, creating an account, updating the password, hitting the post report create endpoint), we should be good.

We also need to do the same process for ruby 2.7.X as we have other apps running in this ruby version.

2021-11-25 19:02 UTC, KevinPedroza commented on 2.6.9/jemalloc/buster-slim/Dockerfile
> +MAINTAINER Patrick Tulskie <patrick@ltvco.com>
Can we update this tag since this is now deprecated?

2021-11-25 19:02 UTC, KevinPedroza commented on 2.6.9/jemalloc/buster/Dockerfile
> +MAINTAINER MinLing Zhao <mzhao@beenverified.com>
Same comment above

2021-11-25 19:09 UTC, KevinPedroza commented on 2.6.9/jemalloc/buster-slim/Dockerfile
> +ENV RUBY_DOWNLOAD_SHA256 5db187882b7ac34016cd48d7032e197f07e4968f406b0690e20193b9b424841f
Also, this SHA256 is for ruby 2.6.6, not 2.6.9.

Same in buster

2021-11-25 19:14 UTC, KevinPedroza requested changes
Small changes above

2021-11-30 17:05 UTC, kamoh commented
Closing in favor of this PR: https://github.com/ltvco/bv-ruby/pull/7

2021-11-30 17:05 UTC, closed without merging